version: '3.8'

services:
  hr_app:
    build: .
    container_name: hrbuddy
    ports:
      - "8501:8501"
    environment:
      - HRBUDDY_CONFIG=${HRBUDDY_CONFIG:-config/default_config.json}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: hr_mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
